{% set name = "pyhash" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhash-{{ version }}.tar.gz
  sha256: cff5c81d613163fc59d623d4546d9be55b46ecd0e573b59057b1bb112a497763

build:
  # Upstream does not support win
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
   - PYTHON_HOME=$PREFIX

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cpuid  # [x86]
    - pip
    - pybind11 >=2.8
    - python
    - setuptools >=42,<58
    # Setup checks for pytest at build time
    - pytest-benchmark
    - pytest-runner
  run:
    - python

test:
  imports:
    - pyhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flier/pyfasthash
  summary: Python Non-cryptographic Hash Library
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
